import enum


class Subservices(enum.IntEnum):
    ENABLE_PERIODIC_HK_GEN = 5
    DISABLE_PERIODIC_HK_GEN = 6
    ENABLE_PERIODIC_DIAGNOSTICS_GEN = 7
    DISABLE_PERIODIC_DIAGNOSTICS_GEN = 8

    REPORT_HK_REPORT_STRUCTURES = 9
    REPORT_DIAG_REPORT_STRUCTURES = 11

    HK_DEFINITIONS_REPORT = 10
    DIAG_DEFINITION_REPORT = 12

    HK_REPORT = 25
    DIAGNOSTICS_REPORT = 26

    GENERATE_ONE_PARAMETER_REPORT = 27
    GENERATE_ONE_DIAGNOSTICS_REPORT = 28

    MODIFY_PARAMETER_REPORT_COLLECTION_INTERVAL = 31
    MODIFY_DIAGNOSTICS_REPORT_COLLECTION_INTERVAL = 32
