import enum


class Subservices(enum.IntEnum):
    COMMAND_MODE_COMMAND = 1
    COMMAND_MODE_COMMAND_FORCES = 2
    COMMAND_MODE_READ = 3
    COMMAND_MODE_ANNOUNCE = 4
    COMMAND_MODE_ANNOUNCE_RECURSIVE = 5
    REPLY_MODE_REPLY = 6
    REPLY_CANT_REACH_MODE = 7
    REPLY_WRONG_MODE_REPLY = 8
